### ISSUE TITLE
kk doesn't open the TUI

### ISSUE THREAD

**Issue by BrendanBall** [nii236/k#3]
This doesn't seem to work. Running `kk` should open the TUI but it just exits straight away without printing anything out. `kk -d` just prints one line saying `INFO[0000] Running in DEBUG mode`.
I expected `kk` to actually open the TUI. The help `help` command doesn't seem to give any more information. It says usage is `kk [global options] command` but the only `command` is `help`.

I would really like to see if this is useful but I can't even get it to do anything :/

**Comment by nii236** [comment]
Hi, thanks for your issue!

Do you have a working kubernetes cluster running and is your config located at ~/.kube/admin.conf?

I admit the app is very rough and definitely needs some work. Hopefully with more feedback and contributions it will become a more useful tool for a wider audience.

**Comment by BrendanBall** [comment]
Hi sorry, I never got a notification. My config is in ~/.kube/config which as far as I know is the default location for `kubectl`. I did however try use your flag `--kubeconfig-path` and it didn't make a difference. `kk -c ~/.kube/config`

**Comment by nii236** [comment]
Thanks for getting back to me! What operating system and version are you running? 

Are you compiling from source? What version of Go?

**Comment by BrendanBall** [comment]
I'm running Linux (with X). 
I compiled from source according to your readme.
Go version: `go version go1.9.2 linux/amd64`
